theme: jekyll-theme-cayman

title: SherlockFog
description: |
    SherlockFog is a tool aimed at network researchers that allows arbitrary topologies to be deployed
    on a local network in order to execute parallel and distributed applications under different network
    conditions.

github:
    is_project_page: true
    repository_name: SherlockFog
    repository_url: https://github.com/sherlockfog/sherlockfog/
    owner_name: Maximiliano Geier
    owner_url: http://github.com/dergeier
